# Copyright (c) 2025 Yeelysia. All rights reserved.

# classification settings -----------------------------------------------------------------------------------------------
num_classes: 10 # (int) number of classes
classes:
  {
    0: 'RS',
    1: 'R1',
    2: 'R2',
    3: 'R3',
    4: 'R4',
    5: 'BS',
    6: 'B1',
    7: 'B2',
    8: 'B3',
    9: 'B4',
  }

# Train settings -------------------------------------------------------------------------------------------------------
device: 'cuda' # (str) device to run on, i.e. cuda, cpu
dataset: '/home/yee/elysiam/dataset/classification' # (str) path to dataset
epochs: 20 # (int) number of epochs to train for
batch_size: 10 # (int) batch size, auto or int

# model settings -------------------------------------------------------------------------------------------------------
model: 'ResNet' # (str) model to use, i.e. YOLO_CLA, ResNet, MobileNetV2, etc.

# criterion settings ---------------------------------------------------------------------------------------------------
criterion: 'CrossEntropyLoss' # (str) criterion to use, i.e. CrossEntropyLoss, BCELoss, etc.

# optimizer settings ---------------------------------------------------------------------------------------------------
optimizer: 'AdamW' # (str) optimizer to use, i.e. AdamW, SGD, etc.
learning_rate: 0.001 # (float) learning rate
weight_decay: 0.001 # (float) weight decay

# scheduler settings ---------------------------------------------------------------------------------------------------
scheduler: 'StepLR' # (str) scheduler to use, i.e. StepLR, CosineAnnealingLR, etc.
step_size: 5 # (int) step size for scheduler
gamma: 0.1 # (float) gamma for scheduler

# visualization settings -----------------------------------------------------------------------------------------------
visible: True # (bool) whether to visualize the training process
num_images: 25 # (int) number of images to visualize


